# Generated by Django 5.0.7 on 2024-07-22 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0004_alter_venda_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venda",
            old_name="produto",
            new_name="produto_vendido",
        ),
        migrations.AlterField(
            model_name="venda",
            name="data",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 22, 16, 13, 9, 563084)
            ),
        ),
    ]
