# Generated by Django 5.0.7 on 2024-07-22 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0005_rename_produto_venda_produto_vendido_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venda",
            name="data",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 22, 16, 15, 37, 827148)
            ),
        ),
    ]
